apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: <your-container-registry>/flaskapp:latest
        ports:
          - containerPort: 5000
        env:
          - name: DATABASE_URL
            value: "mysql://profileapp_user:Frds@123@mysql:3306/profileapp_db"
        command: ["sh", "-c", "python app.py"]

---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flaskapp

