apiVersion: v1
kind: Service
metadata:
  name: flaskapp
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000  # Replace with an available port
  selector:
    app: flaskapp

