apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: <your-docker-image>  # Replace with your Docker image
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysql"

