apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile-container
        image: vadakkan01/profile:0.2  # or your ACR image
        ports:
        - containerPort: 5000

